en/mulesoft/modules/ROOT/pages/ms_composer_prerequisites.adoc
=> W-11069191-FixFlowNotifications-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes.adoc
=> W-11097759-SlackRN-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes.adoc
=> W-11163933-SalesforceRN-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes.adoc
=> W-11233509-WorkdayRN-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_prerequisites.adoc
=> W-11302564-OrgLinking-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11302594-NullValues-ESB

en/mulesoft/modules/ROOT/pages/_partials/null-values.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_netsuite_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_salesforce_reference.adoc
=> W-11365480-MovingInfo-ESB

en/mulesoft/antora.yml
ref: [W-11260414](https://gus.lightning.force.com/a07EE00000yiaYUYAY)
This is part of the Antora 3 upgrade.
- Dead links
=> [W-11260414] update version

en/mulesoft/modules/ROOT/pages/ms_composer_jira_reference.adoc
=> W-11363220-AddAdminJiraPrivs-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_gmail_reference.adoc
=> W-11365480-FixGmailDoc-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_reference.adoc
=> W-11422281-AdjustConnectorPageCopy-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_zendesk_reference.adoc
=> W-11424481-FixingTypo-SG

en/mulesoft/modules/ROOT/nav.adoc
=> W 11424481-FixTOC-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W 11501748 r ns for q2 esb

en/mulesoft/modules/ROOT/nav.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_hubspot_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_hubspot_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc, en/salesforce/src/docs/nav.json
=> W-11496375-HubSpot-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11501748-RequiredFieldsRN-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_http_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11501790-HTTPUpdatesQ2-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11496375-NetSuiteConcurrencyManagement-SG

en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11496375-ComposerPartialRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_salesforce_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11496375-SalesforceV11TriggerConditionsQ2-SG

en/mulesoft/modules/ROOT/nav.adoc, en/mulesoft/modules/ROOT/pages/_partials/http-ki.adoc, en/mulesoft/modules/ROOT/pages/_partials/rpa-ki.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_rpa_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc, en/salesforce/src/docs/ms_composer_rpa_reference.adoc, en/salesforce/src/docs/nav.json
=> W-11503586-RPAConnector-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_servicenow_reference.adoc
=> W-11501748-FixCapitalization-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11501748-FixDate-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11581154-AccessControl-SG

en/mulesoft/modules/ROOT/pages/ms_composer_rpa_reference.adoc
=> W-11573504-FixRPALink-ESB

en/mulesoft/modules/ROOT/nav.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_dynamics_365_business_central_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_ms_dynamics_365_business_central_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc, en/salesforce/src/docs/nav.json
=> W-11581154-MSDynamics365BusinessCentral-SG

en/mulesoft/modules/ROOT/pages/_partials/netsuite-connection-details.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11646899-DataPillRN-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_custom_expression_editor.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11646908-PublishPicklistMapping-ESB

en/mulesoft/modules/ROOT/pages/_partials/binary-data.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_box_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11646927-PublishBinaryDataMapping-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_servicenow_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11646899-HTTPQuickBooksServiceNow

en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11722063-SFComposerBug-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_netsuite_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11722063-NetSuiteBug-SG

en/mulesoft/modules/ROOT/pages/ms_composer_http_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W 11722071 http oauth update esb

en/mulesoft/modules/ROOT/pages/ms_composer_prerequisites.adoc
=> W-11793847-RemoveLine-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_http_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W 11793961 http oauth updates esb

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc
=> W-11794090-HeaderFix-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11860879-ReleaseNote-FI-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11860879-JSONRN-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-18861949-ListOfStringsRN-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_netsuite_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11859001-NetSuiteObjects-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_test_flow.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11862876-ExportAFlow-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11860879-JiraRN-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc
=> W-111860879-TypoFix-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11927317-WorkdayRN-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_stripe_reference.adoc
=> W-11934107-FixStripeFormatting-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_hubspot_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11934107-HUbSpotTriggerUpdates-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11927317-StripeRNs-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-1194107-CustomLogicUpdates-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_prerequisites.adoc
=> W-11934107-APISharing-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_salesforce_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11987101-SalesforceNewOperations-SG

en/mulesoft/modules/ROOT/pages/ms_composer_build_a_flow_using_templates.adoc
=> W-11987101-CustomizingYourTemplate-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_netsuite_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11987101-NetSuiteNewObjects-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11999234-HTTPRNs-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc, en/salesforce/src/docs/nav.json
=> W-11987101-TOC-SG

en/mulesoft/modules/ROOT/nav.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_marketo_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc, en/salesforce/src/docs/nav.json
=> W-11999198-MarketoDoc-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_jira_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_marketo_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11999198-JiraNewOperations-ESB

en/salesforce/src/docs/nav.json
=> W-1999193-FixNavFile-ESB

en/mulesoft/modules/ROOT/nav.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_prerequisites.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_rest_consumer_reference.adoc
=> W-11987101-RestConsumer-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-11720779-NetSuiteBug-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-12060627-RunHistoryRN-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc
=> W-11720779-OpenAccessControlMS-SG

en/mulesoft/modules/ROOT/pages/ms_composer_http_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-12078163-HTTPOAuthV3-SG

en/mulesoft/modules/ROOT/pages/ms_composer_workday_reference.adoc
=> W-12060627-RemoveLineInWorkday-ESB

en/mulesoft/modules/ROOT/nav.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_automation_credits.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_glossary.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_automation_credits.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc, en/salesforce/src/docs/nav.json
=> W-12060925-UsageSummary-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-12138792-ZendeskRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-12138792-ServiceNowRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-12137707-RN-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_rpa_reference.adoc
=> W-12221227-UpdateRPAConnectorDoc-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_netsuite_reference.adoc
=> W-12220359-NetSuiteBundle-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-12220405-SalesforceRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-12272031-Jira-SG

en/mulesoft/modules/ROOT/pages/ms_composer_netsuite_reference.adoc
=> W-12362632-FixIssue-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_http_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc, en/salesforce/src/docs/nav.json
=> W-12362632-HTTPConnectorUpdateAndRN-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12357293-ServiceNowRN-SG

en/salesforce/src/docs/ms_composer_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2021.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc, en/salesforce/src/docs/ms_composer_release_notes_ki.adoc, en/salesforce/src/docs/nav.json
=> W-12362632-KI-POC-ESB

en/mulesoft/modules/ROOT/nav.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes_ki.adoc, en/salesforce/src/docs/ms_composer_release_notes_ki.adoc
=> W-12362632-MSKIPage-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_netsuite_reference.adoc
=> W-12357293-NetSuiteFix-SG

en/mulesoft/modules/ROOT/pages/ms_composer_netsuite_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12362632-NetSuiteConnectorUpdates-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_overview.adoc
=> W-12357267-ComposerUseCases-SG

en/mulesoft/modules/ROOT/pages/ms_composer_gmail_reference.adoc
=> W-12354493-GmailAttachmentClarification-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12438667-NetSuiteRN-SG

en/mulesoft/modules/ROOT/pages/_partials/see-also.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_quickbooks_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12439350-QuickbooksUpdate-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12438667-JiraRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_dynamics_365_business_central_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12439455-MSBusinessCentralUpdates-SG

en/mulesoft/modules/ROOT/nav.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_sage_intacct_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc, en/salesforce/src/docs/ms_composer_sage_intacct_reference.adoc, en/salesforce/src/docs/nav.json
=> W-12362937-SageIntacctRef-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12436918-FixRNDate-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12438667-RestConsumerRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12413431-PlatformUpdateRN-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12508797-HTTPRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_gmail_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12508797-GmailUpdates-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12508797-ZendeskRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12513431-ReleaseNotes-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12586676-PlatformRN-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12587002-JiraRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc
=> W-12587002-RevDate-SG

en/mulesoft/modules/ROOT/pages/ms_composer_workday_reference.adoc
=> W-12522146-WorkdayRoles-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_salesforce_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12594445-ErrorHandlingSalesforce-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12661050-ImportFeature-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12661128-APISharingRN-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_prerequisites.adoc
=> W-12661128-APISharingOrgLinking-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_sage_intacct_reference.adoc
=> W-12661107-SageIntacctUpdates-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12734626-UXEnhancementRNs-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12734688-NetSuiteRNs-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_http_reference.adoc
=> W-12772804-HTTPContentType-SG

en/mulesoft/modules/ROOT/pages/ms_composer_salesforce_reference.adoc
=> W-12734843-UpdateSFConnector-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12735642-JiraRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12981023-XeroRN-ESB

en/mulesoft/modules/ROOT/pages/_partials/trigger-definition.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_hubspot_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_workday_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_xero_reference.adoc
=> W-12981028-FixPolling-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_custom_expression_editor.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13005471-FormulaEditorImprovements-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_google_bigquery_reference.adoc
=> W-12981085-GoogleBigQueryUpdate-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc
=> W-12976948-ComposerRunHistoryTimezone-SG

en/mulesoft/modules/ROOT/pages/ms_composer_workday_reference.adoc
=> W-12965677-WorkdayHostName-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-12977016-QuickBooksRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc
=> W-12981117-ErrorHandlingDoc-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc, en/salesforce/src/docs/ms_composer_rest_consumer_reference.adoc, en/salesforce/src/docs/nav.json
=> W-13066939-FixedIssuesRNs-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_salesforce_reference.adoc
=> W-13067096-TriggerTimer-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13040147-SnowflakeRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13066939-FixRNID-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13066939-NetsuiteRN-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_slack_reference.adoc
=> W-13066939-SlackUpdate-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_jira_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13091877-JiraConnectionField-ESB

en/mulesoft/modules/ROOT/nav.adoc, en/mulesoft/modules/ROOT/pages/_partials/jira-ki.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_jira_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes_ki.adoc, en/salesforce/src/docs/ms_composer_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2021.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc, en/salesforce/src/docs/ms_composer_release_notes_ki.adoc
=> W-13081319-JiraKnownIssues-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13144437-SageRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13144437-SalesforceRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13144437-JiraRN-SG

en/salesforce/src/docs/ms_composer_release_notes_ki.adoc
=> W-13314408-ServiceNowCustomTables-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13272734-SageRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-113260865-NewSearchBarRN-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_asana_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_salesforce_marketing_cloud_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_servicenow_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_stripe_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_twilio_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_workday_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_xero_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_zuora_reference.adoc
=> W-13272710-CustomFields-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-17272734-QuickBooksRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-17272734-NetSuiteRN-SG

en/mulesoft/modules/ROOT/nav.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_sap_s4hana_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc, en/salesforce/src/docs/ms_composer_sap_s4hana_reference.adoc, en/salesforce/src/docs/nav.json
=> W-13511404-SAPS4HANACloud-SG

en/mulesoft/modules/ROOT/pages/ms_composer_netsuite_reference.adoc
=> W-13309966-NetSuiteSetup-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13512960-NetSuiteRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes_ki.adoc, en/salesforce/src/docs/ms_composer_release_notes_ki.adoc
=> W-13563266-SAPS4HANAKnownIssue-SG

en/mulesoft/modules/ROOT/pages/ms_composer_jira_reference.adoc
=> W-13479308-JiraOrgSiteURL-SG

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13594626-ErrorHandlerUnBeta-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc
=> W-13594626-ErrorHandlerUpdates-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13606652-SalesforceRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_servicenow_reference.adoc
=> W-13600941-ServiceNowTables-SG

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc
=> W-13651546-RunHistoryLimit-SG

en/mulesoft/modules/ROOT/pages/ms_composer_prerequisites.adoc
=> W-13595013-ComposerTypo-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13595013-JiraRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13595650-VariablesDoc-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13595013-SalesforceRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13668071-RPAReleaseNote-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13674282-RPARN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13668071-RefreshRN-ESB

CODEOWNERS
=> W-13736152 Update CODEOWNERS

CODEOWNERS
=> W-13736152 Update CODEOWNERS symbol

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13674282-NetSuiteRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13748674-StripeRN-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_rpa_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13748687-RPA-OauthUpdates-ESB

en/mulesoft/modules/ROOT/nav.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_http_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_invocable_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_invocable_flows.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc, en/salesforce/src/docs/nav.json
=> W-13748677-InvocableFlows-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc
=> W-13831928 invocable flow fix

en/mulesoft/modules/ROOT/pages/ms_composer_custom_expression_editor.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13831939-FormulaEditorImprovements

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13915195-SalesforceRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13915195-NetSuiteRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-13985909-JiraRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_prerequisites.adoc
=> W-13985909-ComposerLink-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes_ki.adoc, en/salesforce/src/docs/ms_composer_release_notes_ki.adoc
=> W-13985909-ComposerKI-SG

en/mulesoft/modules/ROOT/pages/ms_composer_prerequisites.adoc
=> W-14010570-ComposerSystemAdm-SG

en/mulesoft/modules/ROOT/pages/ms_composer_prerequisites.adoc
=> W-14004228-ComposerOrgDomain-SG

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_invocable_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-14080610-InvocableFlowsUpdates-SG

en/mulesoft/modules/ROOT/pages/ms_composer_sage_intacct_reference.adoc
=> W-14080963-SageUpdate-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_prerequisites.adoc
=> W-14017095-ComposerRegions-SG

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-14153243-PicklistMappingUpdate-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_invocable_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-14002345-InvocableFlowsOutputs-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes_ki.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc, en/salesforce/src/docs/ms_composer_release_notes_ki.adoc
=> W-14145916-ComposerKI-SG

en/mulesoft/modules/ROOT/pages/ms_composer_invocable_flows.adoc
=> W-14145916-OutputExample-SG

en/mulesoft/modules/ROOT/pages/ms_composer_custom_expression_editor.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-14079200-FormulaEditorPhase2-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-14238005-SAPS4HANARN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_dynamics_365_business_central_reference.adoc
=> W-14244335-MSBusinessCentralCustomFields-SG

en/mulesoft/modules/ROOT/pages/ms_composer_jira_reference.adoc
=> W-14237901-JiraFixes-SG

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_invocable_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-14237887-InvocableFlowsFlowOrchestration-SG

en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-14235912-HubSpotRNForSF-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-14236981-VariablesDoc-ESB

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-14322274-SwapConnections-SG

en/mulesoft/modules/ROOT/pages/ms_composer_snowflake_reference.adoc
=> W-14365009-SnowflakeTriggerBehavior-SG

en/mulesoft/modules/ROOT/pages/ms_composer_http_reference.adoc
=> W-14269599-HTTPRequestBody-SG

en/mulesoft/modules/ROOT/pages/ms_composer_snowflake_reference.adoc
=> W-14365009-SnowflakeTriggerMoreInfo-SG

en/mulesoft/modules/ROOT/pages/ms_composer_snowflake_reference.adoc
=> W-14449941-SnowflakeTriggers-SG

en/mulesoft/modules/ROOT/pages/ms_composer_snowflake_reference.adoc
=> W-14449941-SnowflakeTriggerFix-SG

en/mulesoft/modules/ROOT/pages/ms_composer_build_a_flow_using_templates.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-14329734-TemplateDiscoverability-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-14488713-SalesforceRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc
=> W-14488290-ConnectionsPage-EBM

en/mulesoft/modules/ROOT/pages/ms_composer_snowflake_reference.adoc
=> W-14464865-SnowflakeAccountName-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_quickbooks_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_stripe_reference.adoc
=> W-14589171-QuickBooksPolingFreq-EBM

en/mulesoft/modules/ROOT/pages/ms_composer_glossary.adoc
=> W-14568609-GlossaryH1Fix-SG

en/mulesoft/modules/ROOT/pages/ms_composer_asana_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_box_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_gmail_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_google_bigquery_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_googlesheets_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_hubspot_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_jira_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_marketo_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_netsuite_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-14589171-AddingPollingFreq-EBM

en/mulesoft/modules/ROOT/pages/ms_composer_glossary.adoc
=> W-14568609-GlossaryFixComposer-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_rpa_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_sage_intacct_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_sap_s4hana_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_servicenow_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_slack_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_snowflake_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_zendesk_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-14662099-PollingFreq-EBM

en/mulesoft/modules/ROOT/pages/ms_composer_xero_reference.adoc
=> W-14702218-XeroLimitation-SG

en/mulesoft/modules/ROOT/pages/ms_composer_tableau_reference.adoc
=> W-14794020-TestBranch-EBM

en/mulesoft/modules/ROOT/pages/ms_composer_jira_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_prerequisites.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_salesforce_marketing_cloud_reference.adoc
=> W-14888447-CommentingOutFutureChanges-EBM

en/salesforce/src/docs/ms_composer_release_notes.adoc
=> W-14881110-Add2024RN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_sap_s4hana_reference.adoc
=> W-14875682 Enhancing sap s4hana documentation

en/mulesoft/modules/ROOT/pages/ms_composer_http_reference.adoc
=> W-15020634-HTTPResponseTimeout-SG

en/mulesoft/modules/ROOT/pages/ms_composer_servicenow_reference.adoc
=> W-15050416-ServiceNowSampleData-SG

en/mulesoft/modules/ROOT/pages/ms_composer_invocable_flows.adoc
=> W-15081871-Image-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2024.adoc
=> W-15185851-SalesforceMarketingCloudRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2024.adoc
=> W-15295595-UIDescriptionRN-EBM

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc
=> W-15296045-HeadingFix-SG

en/mulesoft/modules/ROOT/pages/ms_composer_about_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_netsuite_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_supported_data_types_and_formulas.adoc, jp/mulesoft/modules/ROOT/pages/ms_composer_about_flows.adoc
=> W-15245473-TimeZoneUpdate-EBM

en/mulesoft/modules/ROOT/pages/_partials/action-definition.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_netsuite_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_workday_reference.adoc
=> W-15399539-ComposerActionPartialReword-SG

en/mulesoft/modules/ROOT/pages/ms_composer_hubspot_reference.adoc
=> W-15632153-HubSpotObjects-SG

en/mulesoft/modules/ROOT/nav.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_automation_credits.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_automation_credits_2.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_hyperautomation.adoc
=> W-15649712-AutomationPackageUpdate-EBM

en/mulesoft/modules/ROOT/pages/ms_composer_using_actions_in_a_flow.adoc
=> W-15632241-PicklistMappingClarify-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2024.adoc
=> W-15758931-NetSuiteRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2024.adoc
=> W-15886156-MissingRNs-EBM

en/mulesoft/modules/ROOT/pages/ms_composer_ms_dynamics_365_business_central_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_teams_reference.adoc
=> W-15837551-MicrosoftConnectorsAdminConsentFlow-SG

en/mulesoft/modules/ROOT/pages/_rn-templates/rn-template-multi-guided.adoc, en/mulesoft/modules/ROOT/pages/_rn-templates/rn-template-multi.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2021.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc, en/salesforce/src/docs/ms_composer_release_notes_2023.adoc, en/salesforce/src/docs/ms_composer_release_notes_2024.adoc, jp/mulesoft/modules/ROOT/pages/_rn-templates/rn-template-multi-guided.adoc, jp/mulesoft/modules/ROOT/pages/_rn-templates/rn-template-multi.adoc, jp/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, jp/salesforce/src/docs/ms_composer_release_notes_2021.adoc, jp/salesforce/src/docs/ms_composer_release_notes_2022.adoc, jp/salesforce/src/docs/ms_composer_release_notes_2023.adoc
=> W-16048375-FixHeadings-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes_ki.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_netsuite_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_ki.adoc
=> W-15954538-NetsuiteMetadataLimit-EBM

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes.adoc, en/salesforce/src/docs/ms_composer_release_notes_2024.adoc
=> W-16124198-WorkdayRN-SG

en/mulesoft/modules/ROOT/pages/ms_composer_jira_reference.adoc
=> W-16388434-JiraUserPicker-SG

en/mulesoft/modules/ROOT/pages/ms_composer_about_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_connecting_a_flow.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_invocable_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_monitoring.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_netsuite_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_overview.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_salesforce_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_scheduling_polling_invoking_flow.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_using_a_flow_and_creating_trigger.adoc
=> W-16334424-UpdateAltTextComposer-SG

en/mulesoft/modules/ROOT/pages/ms_composer_http_reference.adoc
=> W-16508746-HTTPJSONArray-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes_ki.adoc, en/salesforce/src/docs/ms_composer_release_notes_ki.adoc
=> W-16532124-SalesforceKnownIssue-SG

en/mulesoft/modules/ROOT/pages/ms_composer_http_reference.adoc
=> W-15460646-HTTPConnectorUpdate-EBM

en/mulesoft/modules/ROOT/pages/ms_composer_scheduling_polling_invoking_flow.adoc
=> W-16404049-SchedulerUpdate-EBM

en/mulesoft/modules/ROOT/pages/ms_composer_http_reference.adoc
=> W-16490908-UpdateHTTPConnectorDoc-EBM

en/mulesoft/modules/ROOT/pages/ms_composer_glossary.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_http_reference.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_workday_reference.adoc, en/salesforce/src/docs/ms_composer_release_notes_2022.adoc, jp/salesforce/src/docs/ms_composer_release_notes_2022.adoc
=> W-16866799 Fix double word typos

CODE_OF_CONDUCT.adoc, CONTRIBUTING.md, LICENSE.txt
=> [W-17670413] OSS files update

en/mulesoft/modules/ROOT/pages/ms_composer_stripe_reference.adoc
=> W-17661141-ComposerBadLinks-SG

en/mulesoft/modules/ROOT/pages/ms_composer_invocable_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_salesforce_reference.adoc
=> W-17661183-ComposerHelpLinks-SG

en/mulesoft/modules/ROOT/pages/ms_composer_monitoring.adoc
=> W-12592925-UpdateMonitoringTopic-EBM

en/mulesoft/modules/ROOT/pages/ms_composer_http_reference.adoc
Removed incorrect section from Example Response field
- Dead links
=> W-17615889-UpdateHTTPConnectorDoc-EBM

en/mulesoft/modules/ROOT/pages/ms_composer_scheduling_polling_invoking_flow.adoc
=> W-17072295-SubFlowUpdate-EBM

en/mulesoft/modules/ROOT/pages/ms_composer_invocable_flows.adoc
Removing section about publishing as per Ashley Simmons https://salesforce-internal.slack.com/archives/C025520JX8A/p1736797945060379
- Dead links
=> W-18128734-RemovePublishingServicesDoc-EBM

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes_ki.adoc, en/salesforce/src/docs/ms_composer_release_notes_ki.adoc, jp/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes_ki.adoc, jp/salesforce/src/docs/ms_composer_release_notes_ki.adoc
=> W-18496343-KnownIssuesLinkChange-SG

en/mulesoft/modules/ROOT/pages/_partials/see-also.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_about_flows.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_overview.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_prerequisites.adoc, en/mulesoft/modules/ROOT/pages/ms_composer_reference.adoc
=> W-18406209-ComposerBrokenLinksMore-SG

en/mulesoft/modules/ROOT/pages/ms_composer_ms_release_notes_ki.adoc, en/salesforce/modules/ROOT/pages/ms_composer_release_notes_ki.adoc
=> W-19176552-UpdateRecordLimitations-EBM

CODEOWNERS
=> W-19639866 updaitng codeowner file
